# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_dob', models.DateField()),
                ('transaction_date', models.DateField()),
                ('sample_Sex', models.CharField(choices=[('M', 'M'), ('F', 'F'), ('Other', 'Other')], max_length=5)),
                ('protein1', models.FloatField()),
                ('protein2', models.FloatField()),
                ('protein3', models.FloatField()),
                ('protein4', models.FloatField()),
                ('sample_status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Tested', 'Tested'), ('Returned', 'Returned')], max_length=9)),
            ],
        ),
    ]
