# Generated by Django 2.0.1 on 2018-05-17 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0006_auto_20180218_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sample_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Received', 'Received'), ('Tested', 'Tested'), ('Insufficient', 'Insufficient')], max_length=12),
        ),
    ]
