# Generated by Django 2.0.1 on 2018-05-24 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0008_patient_consent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='consent',
        ),
    ]
