# Generated by Django 2.0.1 on 2018-06-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0010_patient_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='alloantibody_details',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='drug_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='dsa',
            field=models.BooleanField(default=False, verbose_name='DSA'),
        ),
        migrations.AddField(
            model_name='patient',
            name='immuno_used',
            field=models.CharField(choices=[('TORi', 'TORi'), ('CNI', 'CNI'), ('None', 'None')], default='None', max_length=4),
        ),
        migrations.AddField(
            model_name='patient',
            name='misc_info_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='misc_info_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='ns_antibody',
            field=models.BooleanField(default=False, verbose_name='Non-specific'),
        ),
    ]
