# Generated by Django 2.0.1 on 2018-06-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0011_auto_20180603_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='CXCL10_level',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sample',
            name='CXCL9_level',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sample',
            name='biopsy',
            field=models.BooleanField(default=False, verbose_name='biopsy'),
        ),
        migrations.AddField(
            model_name='sample',
            name='ccl2_level',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sample',
            name='injury_risk',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sample',
            name='medication_change',
            field=models.BooleanField(default=False, verbose_name='Medication Change'),
        ),
        migrations.AddField(
            model_name='sample',
            name='repeat_assay',
            field=models.BooleanField(default=False, verbose_name='Repeat Assay'),
        ),
        migrations.AddField(
            model_name='sample',
            name='vgfa_level',
            field=models.FloatField(default=0),
        ),
    ]
