# Generated by Django 2.0.1 on 2018-06-03 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0012_auto_20180603_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='vgfa_level',
            new_name='vegfa_level',
        ),
    ]
