# Generated by Django 2.0.1 on 2018-06-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0013_auto_20180603_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='injury_risk',
            field=models.TextField(default=''),
        ),
    ]
