# Generated by Django 2.0.1 on 2018-06-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0014_auto_20180604_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='graft_lost',
            field=models.BooleanField(default=0),
        ),
    ]
