# Generated by Django 2.0.1 on 2018-06-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0015_patient_graft_lost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dsa',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], default='Negative', max_length=8),
        ),
    ]
