# Generated by Django 3.0.2 on 2020-01-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0017_auto_20180626_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='reason_for_biopsy',
            field=models.CharField(choices=[('Acute Rejection', 'Acute Rejection'), ('Borderline', 'Borderline'), ('Chronic Rejection', 'Chronic Rejection'), ('C4d', 'C4d')], max_length=17),
        ),
    ]
