# Generated by Django 3.0.2 on 2020-01-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0018_auto_20200105_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='CNITac_Sensitivity',
            field=models.BooleanField(default=False, verbose_name='CNI/Tacrolimus sensitivity'),
        ),
        migrations.AddField(
            model_name='patient',
            name='DSA_RF',
            field=models.BooleanField(default=False, verbose_name='DSA'),
        ),
        migrations.AddField(
            model_name='patient',
            name='Previous_Rejection',
            field=models.BooleanField(default=False, verbose_name='Previous Rejection'),
        ),
        migrations.AddField(
            model_name='patient',
            name='Second_Transplant',
            field=models.BooleanField(default=False, verbose_name='Second Transplant'),
        ),
    ]
