# Generated by Django 3.0.2 on 2020-01-22 07:39

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0019_auto_20200105_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='biopsy_result',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='reason_for_biopsy',
        ),
        migrations.AddField(
            model_name='sample',
            name='adtl_risk_factors',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('DSA', 'DSA'), ('Previous_Rejection', 'Previous Rejection'), ('Second_Transplant', 'Second Transplant')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='creatinine_baseline',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='creatinine_current',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='eGFR',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='immunosuppression',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='biopsy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_biopsy', models.DateField()),
                ('result_for_biopsy', models.CharField(choices=[('Normal', 'Normal'), ('Acute Rejection', 'Acute Rejection'), ('Borderline', 'Borderline'), ('Chronic Rejection', 'Chronic Rejection'), ('C4d', 'C4d')], max_length=17)),
                ('biopsy_result', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='samples.Patient')),
            ],
        ),
    ]
