# Generated by Django 3.0.2 on 2020-01-22 08:47

from django.conf import settings
from django.db import migrations, models
import samples.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('samples', '0020_auto_20200122_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='biopsy',
            name='submitting_group',
            field=models.ForeignKey(default=3, on_delete=samples.models.DefaultGroup.get_default, to='auth.Group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biopsy',
            name='submitting_user',
            field=models.ForeignKey(default=2, on_delete=samples.models.DefaultGroup.get_default, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
