# Generated by Django 3.0.2 on 2020-01-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0021_auto_20200122_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='graft_lost_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='immuno_used',
            field=models.CharField(choices=[('TORi', 'TORi'), ('CNI', 'CNI'), ('MMF', 'MMF'), ('Steroids', 'Steroids'), ('Immuran', 'Immuran'), ('None', 'None')], default='None', max_length=8),
        ),
    ]
