# Generated by Django 3.0.2 on 2020-02-12 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0022_auto_20200129_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biopsy',
            old_name='biopsy_result',
            new_name='biopsy_notation',
        ),
    ]
