# Generated by Django 3.0.2 on 2020-02-13 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0023_auto_20200212_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='misc_info_1',
            new_name='primary_kidney_disease',
        ),
    ]
