# Generated by Django 3.0.2 on 2020-02-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0024_auto_20200213_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='graft_lost_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
