# Generated by Django 3.0.2 on 2020-02-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0025_auto_20200213_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='adtl_risk_factors',
        ),
        migrations.AddField(
            model_name='sample',
            name='BkV',
            field=models.BooleanField(default=False, verbose_name='BkV'),
        ),
        migrations.AddField(
            model_name='sample',
            name='EBV',
            field=models.BooleanField(default=False, verbose_name='EBV'),
        ),
    ]
